### ISSUE TITLE
[Bug]: Program doesn't launch after installing and running hi_getter

### ISSUE THREAD

**Issue by ChristianVaughn** [Cubicpath/HaloInfiniteGetter#119]
### What happened?

I am on python 3.10.11 and i installed via pip. I have tried to run hi_getter, but nothing happens. no error is thrown, and no program window pops up. Is there anything I can try to get the program launching? I also tried running python -m hi_getter and it gave the output below

### Version

v0.13

### What operating system are you using?

Windows

### Relevant log output

```
PS C:\Users\user> python -m hi_getter
Sub class of QObject not inheriting QObject!? Crash will happen when using Client.
Sub class of QObject not inheriting QObject!? Crash will happen when using VersionChecker.
Sub class of QObject not inheriting QObject!? Crash will happen when using _SignalHolder.
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\micro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\hi_getter\__main__.py", line 16, in <module>
    exit_code: int = main(*sys.argv)
  File "C:\Users\micro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\hi_getter\run.py", line 28, in main
    GetterApp.create(*args)
  File "C:\Users\micro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\hi_getter\models.py", line 430, in create
    cls.__init__(cls.__instance, *args, **kwargs)
  File "C:\Users\micro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\hi_getter\gui\app.py", line 103, in __init__
    self.session: NetworkSession = NetworkSession(self)
  File "C:\Users\micro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\hi_getter\network\manager.py", line 167, in __init__
    self.manager: QNetworkAccessManager = QNetworkAccessManager(manager_parent)
TypeError: 'PySide6.QtNetwork.QNetworkAccessManager.__init__' called with wrong argument types:
  PySide6.QtNetwork.QNetworkAccessManager.__init__(GetterApp)
Supported signatures:
  PySide6.QtNetwork.QNetworkAccessManager.__init__(Optional[PySide6.QtCore.QObject] = None)```

**Comment by Cubicpath** [comment]
Hi, I took a look and it seems like the latest changes to PySide6 broke some things. I'll make a patch for it but in the meantime you should be good if you downgrade to last tested version, PySide6 v6.4.2.

```
pip install pyside6_essentials==6.4.2
```

**Comment by ChristianVaughn** [comment]
Thanks for the reply. That seemed to fix everything
