### ISSUE TITLE
[Bug]: `shiboken6` incompatibility with `pywin32`

### ISSUE THREAD

**Issue by Cubicpath** [Cubicpath/HaloInfiniteGetter#82]
### Contact Details

cubicpath@pm.me

### What happened?

I've noticed a very obscure and problematic bug that can cause crashes on startup. Unfortunately I can no longer replicate this, so it may be slightly inaccurate, but here is the rundown of what is causing the crash:

The `has_package` util calls `WorkingSet()` from `pkg_resources`, which loads all modules installed in the current environment. Somewhere along here, a `shibokensupport` module is dynamically created (supposedly from `shiboken6`) and hooks on to the Python import. When `pkg_resources` then tries to load the `pywin32_system32` module, a `SyntaxError` is raised. It is my assumption that `shibokensupport` is trying to read the `pywintypes310.dll` file as a python module.

Uninstalling `pywin32`, or just removing the `pywin32_system32` module solves the crashing. In some cases, installing all optional dependencies of HaloInfiniteGetter also solved the crashing. Additionally, running the program with the PyCharm debugger attached also causing zero crashes. I'll attempt to investigate this further but wanted to document it while I had the chance.

### Version

v0.13a1

### What operating system are you using?

Windows

### Relevant log output

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\tokenize.py", line 332, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "%:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Projects\Programs\Python\HaloInfiniteGetter\src\hi_getter\__main__.py", line 16, in <module>
    exit_code: int = main(*sys.argv)
  File "C:\Projects\Programs\Python\HaloInfiniteGetter\src\hi_getter\run.py", line 28, in main
    GetterApp.create(*args)
  File "C:\Projects\Programs\Python\HaloInfiniteGetter\src\hi_getter\models.py", line 459, in create
    cls.__init__(cls.__instance, *args, **kwargs)
  File "C:\Projects\Programs\Python\HaloInfiniteGetter\src\hi_getter\gui\app.py", line 132, in __init__
    self._register_archive_formats()
  File "C:\Projects\Programs\Python\HaloInfiniteGetter\src\hi_getter\gui\app.py", line 227, in _register_archive_formats
    if not has_package('py7zr'):
  File "C:\Projects\Programs\Python\HaloInfiniteGetter\src\hi_getter\utils\package.py", line 142, in has_package
    from pkg_resources import WorkingSet
  File "C:\Projects\Programs\Python\HaloInfiniteGetter\venv\lib\site-packages\pkg_resources\__init__.py", line 74, in <module>
    from pkg_resources.extern import appdirs
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "C:\Projects\Programs\Python\HaloInfiniteGetter\venv\lib\site-packages\pkg_resources\extern\__init__.py", line 52, in create_module
    return self.load_module(spec.name)
  File "C:\Projects\Programs\Python\HaloInfiniteGetter\venv\lib\site-packages\pkg_resources\extern\__init__.py", line 37, in load_module
    __import__(extant)
  File "C:\Projects\Programs\Python\HaloInfiniteGetter\venv\lib\site-packages\pkg_resources\_vendor\appdirs.py", line 560, in <module>
    import win32com.shell
  File "C:\Projects\Programs\Python\HaloInfiniteGetter\venv\lib\site-packages\win32com\__init__.py", line 6, in <module>
    import pythoncom
  File "C:\Projects\Programs\Python\HaloInfiniteGetter\venv\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "shibokensupport/signature/loader.py", line 61, in feature_imported
  File "shibokensupport/feature.py", line 137, in feature_imported
  File "shibokensupport/feature.py", line 148, in _mod_uses_pyside
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 1147, in getsource
    lines, lnum = getsourcelines(object)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 1129, in getsourcelines
    lines, lnum = findsource(object)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 954, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\tokenize.py", line 396, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\tokenize.py", line 373, in detect_encoding
    encoding = find_cookie(first)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\tokenize.py", line 337, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'C:\\Projects\\Programs\\Python\\HaloInfiniteGetter\\venv\\lib\\site-packages\\pywin32_system32\\pywintypes310.dll'

Process finished with exit code 1

```

**Comment by Cubicpath** [comment]
Note that `pywin32` has no relation to HaloInfiniteGetter other than being installed in the same Python environment. Why this is an issue that is even possible in the first place I still don't understand. Arbitrary code should not be ran when searching through package metadata.

**Comment by Cubicpath** [comment]
## Problem

Source for the culprit `shibokensupport` functions, which are loaded in with an `EmbeddableZipImporter` (I assume from raw data located in a shiboken DLL). As expected, there is an import hook which calls these functions.

```python3
def feature_imported(module):
    # PYSIDE-2029: Need to inspect imported modules for PySide usage.
    """
    Set the module feature default after import.

    A module that uses PySide has a switching default of 0 = "no feature".
    Otherwise the default is -1 = "ignore this module".
    """
    name = module.__name__
    if name not in pyside_feature_dict:
        pyside_feature_dict[name] = 0 if _mod_uses_pyside(module) else -1


def _mod_uses_pyside(module):
    """
    Find out if this module uses PySide.

    Simple approach: Search the source code for the string "PySide6".
    Maybe we later support source-less modules by inspecting all code objects.
    """
    try:
        source = inspect.getsource(module)
    except TypeError:
        # this is a builtin module like sys
        return False
    except OSError:
        # this is a module withot source file
        return False
    return "PySide6" in source
```

Once `pywintypes310.dll` is loaded through the `__import_pywin32_system_module__` function from `pywin32`, `_mod_uses_pyside` attempts to read said DLL as a python module. As there is no handler for a `SyntaxError`/`UnicodeDecodeError` exception, it crashes.

## Solution
Now that the source is found, I can wrap the `shibokensupport.feature._mod_uses_pyside` function with an `except SyntaxError`, like so:

```python3

def patch_incompatible_pywin32_shibokensupport__mod_uses_pyside():
    import shibokensupport

    def patch(func):
        def wrapper(*args, **kwargs):
            try:
                func(*args, **kwargs)
            except SyntaxError as e:
                print(f'{shibokensupport.__name__}: {e}')

        return wrapper

    shibokensupport.feature._mod_uses_pyside = patch(shibokensupport.feature._mod_uses_pyside)

patch_incompatible_pywin32_shibokensupport__mod_uses_pyside()
```

What would normally crash and emit that horrible stack trace now succeeds and prints:
```
shibokensupport: invalid or missing encoding declaration for 'C:\\Projects\\Programs\\Python\\HaloInfiniteGetter\\venv\\lib\\site-packages\\pywin32_system32\\pywintypes310.dll'
shibokensupport: invalid or missing encoding declaration for 'C:\\Projects\\Programs\\Python\\HaloInfiniteGetter\\venv\\lib\\site-packages\\pywin32_system32\\pythoncom310.dll'
```
